# Generated by Django 2.2.8 on 2019-12-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinolists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinolist',
            name='character',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='dinolist',
            name='overview',
            field=models.CharField(max_length=5000),
        ),
    ]
